### ISSUE TITLE
[BUG]: Tag filter is confusing

### ISSUE THREAD

**Issue by lyndseybrowning** [thisdot/framework.dev#159]
**Describe the bug**
I'm not sure if this is actually a bug or if it's intentional, but when I search for `test` inside the `tag` dropdown in the Advanced Filter, I'm seeing results that don't make sense to me. It seems like the filter results are randomised somehow.

**To Reproduce**
1. Go to https://react.framework.dev/
2. Type `react` into the search bar and click "Search"
3. Click the "Advanced Search" button
4. Enter "test" into the "Tags" field
5. See that the options in the list are unexpected.

**Expected behavior**
I would expect only items containing the search term I enter to be present in the dropdown list.

**Screenshots**

**Brave**:
![image](https://user-images.githubusercontent.com/3502195/151157339-4a51a6f9-2b38-4c04-884c-3228cf5307e2.png)
![image](https://user-images.githubusercontent.com/3502195/151157847-d1c4567b-bba3-494c-8636-08fb10cc8a4a.png)
![image](https://user-images.githubusercontent.com/3502195/151157960-f373675f-f6fe-4cf4-92b9-b04b294be2cd.png)

**Chrome**:
![image](https://user-images.githubusercontent.com/3502195/151158343-551e3502-e5c7-4770-9851-e9cf41c91195.png)

**Desktop (please complete the following information):**
 - iOS
 - Brave & Chrome tested
 - Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)
 - Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
N/A

**Comment by jbachhardie** [comment]
We're currently using a fuzzy search algorithm so yes, in a way this is "intentional". There's probably a case to be made to tweak the sensitivity so it's less confusing, though.
