### ISSUE TITLE
[BUG] There's no such command as yarn dev 

### ISSUE THREAD

**Issue by RinatValiullov** [thisdot/framework.dev#170]
**Describe the bug**
There is no such command (npm script) as `yarn dev` in `package.json` file

**To Reproduce**
1. Go to the root folder
2. Type command (npm script) in your terminal: `yarn install`
3. Type command (npm script) in your terminal: `yarn dev`
4. See error in the terminal: _Command "dev" not found._

**Expected behavior**
Command `yarn dev` must run all servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/9755333/157518671-003bb9e8-cb68-4118-889c-6b9c3c97fc71.png)

![image](https://user-images.githubusercontent.com/9755333/157518749-53e49dcd-57c3-4a86-b3f2-b2dc6ddc3c89.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Version 20H2]
 - Browser [chrome]
 - Version [99.0.4844.51]

**Comment by jbachhardie** [comment]
Thank you for reporting this. It's actually a documentation problem, the command was removed because running the three different sites at once isn't really advisable but we forgot to update the docs. I'll fix that.
