### ISSUE TITLE
[BUG] Featured libraries text is hard coded to React

### ISSUE THREAD

**Issue by lindakatcodes** [thisdot/framework.dev#186]
**Describe the bug**
When running the Angular version locally, noticed that the library section says "Featured React libraries". Looking inside the code, this text (React) is hard coded into the site. Will want this to be dynamic based on the version of the site you're on.

**To Reproduce**
1. Run `yarn dev:angular` and load the localhost page
2. Scroll down to the featured libraries section of the homepage

**Expected behavior**
Text should read "Featured Angular libraries"

**Screenshots**
<img width="1410" alt="Screen Shot 2022-04-13 at 5 53 20 PM" src="https://user-images.githubusercontent.com/16214572/163284854-9714abb3-aa9f-409a-810b-396192781a40.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey 12.3.1
 - Browser: Chrome
 - Version 100

**Comment by lindakatcodes** [comment]
Going to take a crack at fixing this! :)

**Comment by iaremarkus** [comment]
Figured I'd sort this, but also happy to remove my PR if you still want to do this yourself @lindakatcodes 😊🙏

**Comment by lindakatcodes** [comment]
Go right ahead, @iaremarkus ! I might not have a chance to get back to this for a little bit, so if you've already got a PR ready that's fine with me. :)
