### ISSUE TITLE
Enhanced visibility of the Compare feature

### ISSUE THREAD

**Issue by RickConrades** [thisdot/framework.dev#231]
**Describe the solution you'd like**
The availability of the current Compare feature is not as evident as we would like for this high-level feature. Design has provided additions to bring this feature more attention. This update is applicable to all framework versions

**Describe alternatives you've considered**
Using the figma [here](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2309%3A118086), add the following:

- add the bottom version of the "Onboarding" options (yellow bar with ability to close) 
- add the top version of the "More Noticeable Bar" option (button positions have been moved and recolored)

**Comment by gunesnt** [comment]
Hello, I want to work on this issue. Can I claim it?

**Comment by dustinsgoodman** [comment]
Hi @gunesnt - thanks for showing interest in working on this issue. We have an internal team member working on this already though. If there are other issues you'd like to work on, please let us know, but we'd hate for you to double the effort of someone else that's already in flight.

**Comment by gunesnt** [comment]
> Hi @gunesnt - thanks for showing interest in working on this issue. We have an internal team member working on this already though. If there are other issues you'd like to work on, please let us know, but we'd hate for you to double the effort of someone else that's already in flight.

@dustinsgoodman Alright, thank you for informing
