### ISSUE TITLE
Feature: add prettier rule for quotes

### ISSUE THREAD

**Issue by jesus4497** [thisdot/framework.dev#239]
**Is your feature request related to a problem? Please describe.**
Currently there are no rules for quotes in the code, it would be good to add single quotes to the prettier rules in order to have an standard in the project.

**Describe the solution you'd like**
Add single quotes to prettier rules

**Comment by francisco-guilherme** [comment]
Hi @jesus4497, thanks for reaching out.

We use double quotes as the standard for our project and we rely on the default prettier [rules](https://prettier.io/docs/en/options.html#quotes), in order to enforce it.
