### ISSUE TITLE
[BUG]: cli messages when running the project locally

### ISSUE THREAD

**Issue by orama254** [thisdot/framework.dev#252]
**Describe the bug**
I'm getting some prompts on the cli when running the project locally.

**To Reproduce**
Following the project contribution guidelines as described [Here](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)

**Expected behavior**
A terminal without the warnings, but with the usual dev environment prompts

**Screenshots**

![framework-dev-astro-error](https://user-images.githubusercontent.com/50571688/193773140-f663ada4-d69b-4543-8909-915ca35e5db0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 [WSL2 Ubuntu 20.04]
 - Browser: Chrome
 - Version: Latest

**Comment by jnalei** [comment]
Current screenshot of errors as of today:

<img width="788" alt="Screen Shot 2022-11-22 at 3 43 32 PM" src="https://user-images.githubusercontent.com/90362911/203455684-c8f96fdf-20b2-4f5d-b725-b512de5333c7.png">

**Comment by jnalei** [comment]
Once we migrate to Vite from Snowpack, the `innerHTML` error should get resolved on its own.
