### ISSUE TITLE
[BUG] Link for Zustand leads to 404 page (React site)

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#253]
**Describe the bug**
When you click on the Zustand link under the React state management section, it leads to a 404 page
<img width="467" alt="Screen Shot 2022-10-06 at 8 11 11 AM" src="https://user-images.githubusercontent.com/67210629/194350266-63ffd6f4-2b38-4901-b2a0-0136b65f1060.png">

**To Reproduce**
1. Go to https://www.framework.dev/
2. Click on React resources
3. Click on libraries > state management
4. Scroll down to click on the Zustand link 

**Expected behavior**
should lead to a valid page. 

**Screenshots**
<img width="490" alt="Screen Shot 2022-10-06 at 8 12 34 AM" src="https://user-images.githubusercontent.com/67210629/194350606-fd9f1613-5df9-4d2f-98ef-01fb9a7504d1.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by Olyno** [comment]
Hi 👋🏻 Can i be assigned to this issue? Also is it okay if i edit the ``image`` and ``href`` links togeather?

**Comment by jdwilkin4** [comment]
I have assigned you to this issue.
If you leave a comment on the other issue too, then I can assign you there as well 👍
