### ISSUE TITLE
[BUG] Multiple Broken images on the react framework site

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#254]
**Describe the bug**
I have found several broken images on the react site. 

### Libraries
<img width="476" alt="Screen Shot 2022-10-06 at 8 07 43 AM" src="https://user-images.githubusercontent.com/67210629/194349419-0a6b0a3a-4fe9-4552-9139-118cdc22fbd9.png">

### Tools
<img width="497" alt="Screen Shot 2022-10-06 at 8 17 36 AM" src="https://user-images.githubusercontent.com/67210629/194351873-49f03fdb-c310-4bcc-bd87-d60f0c6e2a09.png">

### Courses
<img width="484" alt="Screen Shot 2022-10-06 at 8 17 57 AM" src="https://user-images.githubusercontent.com/67210629/194351962-1bfd4ad6-4173-4981-bf08-74e2690b969f.png">

### Podcasts
<img width="306" alt="Screen Shot 2022-10-06 at 8 18 51 AM" src="https://user-images.githubusercontent.com/67210629/194352188-f324a5c0-be76-4ab1-a4bd-1d7b6d0dcf2e.png">

### Books
<img width="329" alt="Screen Shot 2022-10-06 at 8 19 15 AM" src="https://user-images.githubusercontent.com/67210629/194352286-28413c01-5f35-4368-8d85-abc468b21d2f.png">

**Expected behavior**
Images should show up for each resource.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by Olyno** [comment]
Hi 👋🏻 I also completed this issue which is related to #253 😄
