### ISSUE TITLE
Add social media sharing to all sites

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#257]
# Issue

As a user, I should be able to share any of the framework.dev sites and see the appropriate image, site image, and description.

- Framework.dev landing site is missing social metadata, social sharing image, and description
- ALL sub Framework.dev sites are missing social metadata, social sharing image, and description

# Requirements

Add social media sharing capabilities to the meta for each site. Each framework site, including the landing page, should feature a templated image corresponding to the site shared.

# Acceptance

Image and site description should work for the following social media sites
- [x] twitter
- [x] facebook
- [x] linkedin

**Comment by Atrophius** [comment]
Designers provided instructions on how to create the images based on a template in Figma. You can find a tutorial video below along with links to the relevant sections in Figma. Let me know if you are missing access and we'll get it for you.

- [Loom tutorial](https://www.loom.com/share/8d703c1eb2e548af96ceb6f09d028485)
- [Open graph image](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2725%3A130781)
- [Hero Graphic](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2731%3A128595)
- 
[Logos](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2732%3A129089)
- [Color seeds to build a theme](https://www.figma.com/file/3cAQKdlEpCrz7dgeKzJEqQ/Framework-library?node-id=9276%3A22559)

**Comment by dustinsgoodman** [comment]
**Title**
- Homepage: <Framework> Framework.dev
  - ex) For React: "React Framework.dev"
- Subpages: <Category> | <Framework> Framework.dev
  - ex) https://react.framework.dev/categories/libraries -> "Libraries | React Framework.dev"

**Description**
Search, compare, and discover top <Framework> libraries and community-driven resources in <Framework>.


@Atrophius let's use the above

**Comment by Atrophius** [comment]
There's also a typo on the homepage of each framework site. Add the missing hypen to "community driven" so that it's "community-drive"

**Comment by morgnism** [comment]
**OG tag base requirements:**
- Titles no longer than 50 - 60 characters
- Descriptions no longer than 155 - 160 characters

**Facebook tag requirements:**
- Image size max 8MB
- Image dimensions 1200 x 630

**Twitter requirements**
- Title no longer than 70
- Image size max 5MB

**LinkedIn requirements**
- Image dimension 1200 x 600

---

- Generate new images to a base 1200 x 600
- Get description copy validated once added
- Verify all socials here https://socialsharepreview.com/

**Comment by morgnism** [comment]
#360

**Comment by jdwilkin4** [comment]
This issue has been resolved and merged in PR #360
