### ISSUE TITLE
Communities dropdown filter on meetups and conferences

### ISSUE THREAD

**Issue by Atrophius** [thisdot/framework.dev#261]
For framework.dev, update "Communities" to have dropdown to filter on meetups and conferences. Design should match existing "libraries" UI.

Data will be provided by marketing and needs to just be uploaded to JSON and launched

**Comment by Atrophius** [comment]
Spreadsheet for all the conferences: https://docs.google.com/spreadsheets/d/1jGZyAFVS4Z8rWwZJ1J_aqRk6JY5pfOutFlLBv7-nqUU/edit?usp=sharing

The General tab goes on all of the framework sites and then the specific tabs go on their sites. Let me know if there are any questions.

**Comment by jdwilkin4** [comment]
PR #335
