### ISSUE TITLE
Verify framework.dev google analytics works

### ISSUE THREAD

**Issue by kahlie-huff** [thisdot/framework.dev#262]

**Comment by morgnism** [comment]
Added the environment variables for each framework site with unique tag ids.

Analytics has been recording for the last 48 hours so **moving to closed**

**Comment by morgnism** [comment]
Relate PRs:
https://github.com/thisdot/framework.dev/pull/327
https://github.com/thisdot/framework.dev/pull/328
https://github.com/thisdot/framework.dev/pull/336
