### ISSUE TITLE
[sveltekit-pod] 2. Add social image and description

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#263]
# Add framework social image and description

## Background

As an user I would like to have the possibility to share the site on social media and for it to have a nice image and description defined, so that it will increase its visibility and shareability

## Acceptance

- [x] Add metadata description
- [x] Add social image
- [x] Test the site on "https://socialsharepreview.com/"

**Comment by asincole** [comment]
@iansamz is there any PR for this you need me to review? I can't seem to find a linked PR

**Comment by iansamz** [comment]
I can't seem to link it's:  https://github.com/thisdot/starter.dev/pull/392/

**Comment by asincole** [comment]
approved

**Comment by iansamz** [comment]
I noticed I made a mistake, as I addressed social share for starter.dev instead of framework.dev. Let me create a new issue which is addressed by my PR for starter.dev.

**Comment by iansamz** [comment]
I noticed I made a mistake, as I addressed social share for starter.dev instead of framework.dev. Let me create a new issue which is addressed by my PR for starter.dev.
