### ISSUE TITLE
[sveltekit-pod] 0. Setup local machine

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#265]
# Setup framework.dev on your local machine

## Background

As a developer I would like a version of framework.dev to be setup and working on my local machine, so that I can develop my tasks.

## Acceptance

- [x] Setup local development
- [x] Setup environment for test storybook (packages/system)

## Notes:

This task need to be completed by all members of the team, so it should be duplicated accordingly.

**Comment by iansamz** [comment]
I have set this up locally.
Working fine
