### ISSUE TITLE
[sveltekit-pod] 1. Create basic folder and files

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#266]
# Add all required folder and files to ensure site works

## Background

As a developer I would like to initialize my framework.dev specific framework site so that the rest of the team and contributor can add content to make it useful for the wider community.

## Acceptance

- [x] Add all Data files
- [x] Add all Script required for development and production release in package.json

## Notes:
- This ticket is NOT going to tackle the addition of the current site on amplify. This is going to be handled by another ticket.

**Comment by asincole** [comment]
PR link: https://github.com/thisdot/framework.dev/pull/307
