### ISSUE TITLE
[solidjs-pod] 3. Add framework to amplify

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#272]
# Add framework in amplify config

## Background

Each framework.dev site is deployed from the same codebase using amplify. In this ticket, we are adding this new framework to be added to the amplify config so that it gets deployed correctly

## Acceptance

- [x] Add the new framework on amplify.yml
- [ ] Test the created PR to make sure that the deployment works as expected

## NOTE:
- You may require someone with AWS access to create the project for you.

**Comment by kodejuice** [comment]
@dustinsgoodman how do we get the projected created on Amplify?

**Comment by dustinsgoodman** [comment]
@kodejuice once the config is ready and merged, we need to set it up in amplify. You'll need me for that. Schedule 15 minutes with me.

**Comment by kodejuice** [comment]
The PR is already up #315
