### ISSUE TITLE
[qwik-pod] Add content for Books

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#285]
# Add books content for framework

## Background

As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Books content to keep me informed and find this site to be resourceful and useful.

## Acceptance

- [ ] Research a list of Books
- [ ] Add the Books information in the data files
- [ ] Test each individual look and external link

NOTE:
- This task is timeboxed to a maximum of 4 hours.
- O'Really is a very good resource for this.

**Comment by AllStackDev1** [comment]
I researched on the 19 of Oct and there seems to be no content for books yet, so I am moving this back to a later date.

**Comment by Zelig880** [comment]
Just invest 30 minutes to see if anything new was published

**Comment by SDaian** [comment]
Search through Google and O'really, since the maturity of the Framework still we don't have anything for Books

**Comment by kenslachtajr** [comment]
None available at this time. Moving to Done for now.
