### ISSUE TITLE
[qwik-pod] Add content for Courses

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#288]
# Add Courses content for framework

## Background

As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Courses content to keep me informed and find this site to be resourceful and useful.

## Acceptance

- [ ] Research a list of Courses
- [ ] Add the Courses information in the data files
- [ ] Test each individual look and external link

NOTE:
- This task is timeboxed to a maximum of 4 hours.

**Comment by AllStackDev1** [comment]
I researched on the 19 of Oct and there seems to be no content for books yet, so I am moving this back to a later date.

**Comment by Zelig880** [comment]
Just invest 30 minutes to see if anything new was published

**Comment by SDaian** [comment]
Spent a few minutes searching in Google if there is anything to share in the Courses tab but without luck, all of the things are presentations.

**Comment by kenslachtajr** [comment]
Add Misko’s JSDrops to this and let's move this to In Review.
