### ISSUE TITLE
[solidjs-pod] Add content for Books

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#290]
# Add books content for framework

## Background

As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Books content to keep me informed and find this site to be resourceful and useful.

## Acceptance

- [ ] Research a list of Books
- [ ] Add the Books information in the data files
- [ ] Test each individual look and external link

NOTE:
- This task is timeboxed to a maximum of 4 hours.
- O'Really is a very good resource for this.

**Comment by kodejuice** [comment]
Blocked:
Seems like there are no SolidJS books yet

**Comment by dustinsgoodman** [comment]
Rather than blocking - let's make sure there's a proper empty state and complete this as a 0 book section for now. These are growing communities so we won't always be able to fill in all the sections but we want to make sure the site looks decent.

**Comment by kodejuice** [comment]
done
