### ISSUE TITLE
[solidjs-pod] Add content for Blog

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#296]
# Add blogs content for framework

## Background

As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Blog content to keep me informed and find this site to be resourceful and useful.

## Acceptance

- [x] Research a list of Blogs (at least 8-10 blogs)
- [x] Add the blog information in the data files
- [x] Test each individual look and external link

NOTE:
- This task is timeboxed to a maximum of 4 hours.

**Comment by mbicknese** [comment]
- https://dev.to/ryansolid [blog]
- https://admin.indepth.dev/author/ryan-carniato/ [blog]
- https://www.thisdot.co/blog/solidjs-fundamentals-and-building-your-first-solidjs-app [article]
- https://www.loginradius.com/blog/engineering/guest-post/introduction-to-solidjs/ [article]
- https://blog.logrocket.com/build-task-tracker-solidjs-typescript/ [article]
