### ISSUE TITLE
[sveltekit-pod] Add content for Blog

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#298]
# Add blogs content for framework

## Background

As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Blog content to keep me informed and find this site to be resourceful and useful.

## Acceptance

- [x] Research a list of Blogs (at least 8-10 blogs)
- [x] Add the blog information in the data files
- [x] Test each individual look and external link

NOTE:
- This task is timeboxed to a maximum of 4 hours.

**Comment by iansamz** [comment]
https://joyofcode.xyz/categories/svelte
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started
https://www.freecodecamp.org/news/search?query=svelte
https://dev.to/t/svelte
https://dev.to/t/sveltekit
