### ISSUE TITLE
[BUG] Broken image link for Views on Vue podcas

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#351]
**Describe the bug**
The Views on Vue podcast has a broken image link
It needs to be replaced a new image.

**To Reproduce**
1. Go to https://www.framework.dev/
2. Click on Vue resources
3. Click on podcasts
4. See the broken image link for the Views on Vue podcast

**Expected behavior**
An image should display

**Screenshots**
<img width="284" alt="Screen Shot 2022-10-26 at 12 36 46 PM" src="https://user-images.githubusercontent.com/67210629/198120233-ae73d8f9-a28d-49dd-b93a-201c90042299.png">

If you are interested in working on this issue, please comment below and it will be assign to you. 
If this is your first time working with framework.dev, then please read through the [Code of Conduct](https://github.com/thisdot/framework.dev/blob/bc69377ddeda5c5fa75093fcdcf9ae8a6858fd5d/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/thisdot/framework.dev/blob/bc69377ddeda5c5fa75093fcdcf9ae8a6858fd5d/CONTRIBUTING.md) documentation. 

This assignment will be given out on a first come basis.

**Comment by aksy2512** [comment]
Hi, Please assign this issue to me

**Comment by jdwilkin4** [comment]
@aksy2512 

It has been assigned to you

**Comment by aksy2512** [comment]
Thank you, I have created a pull request for the same:- https://github.com/thisdot/framework.dev/pull/352
