### ISSUE TITLE
[chore] Remove the following conferences from all framework.dev sites

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#359]
### Remove from all three sites (react, angular and vue)
- [ ] DevOps Days Brazil
- [ ] DevOps Days India
- [ ] Pass Data Community Summit
- [ ] Data Science Global Summit
- [ ] Cyber Security Cloud Conference
- [ ] DevOps day LA
- [ ] SXSW
- [ ] JavaLand 2023

### Change the following images

- [ ] replace the XtremeJS logo with one that does not reference the year
- [ ] replace Remix conf logo with one that does not reference the year

**Comment by dustinsgoodman** [comment]
You should leave the following:

- World of no code conf
- Global summit for node.js 23 (but rename to remove the node version/year)
- Node congress
- Web3 Tech Summit
- CSS day conf

**Comment by jdwilkin4** [comment]
@dustinsgoodman 

I updated the list 👍
