### ISSUE TITLE
[BUG] Keen UI logo missing

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#363]
**Describe the bug**
Keen UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

<img width="438" alt="Screen Shot 2022-10-29 at 12 50 37 PM" src="https://user-images.githubusercontent.com/1815379/198845963-24b85de0-360e-4465-8bfd-9916ce715306.png">

We can use the logo from https://madewithvuejs.com/keen-ui

**Comment by zafar-hussain** [comment]
Hi @dustinsgoodman,

Please assign this issue to me,

cheers
