### ISSUE TITLE
[BUG] Mint UI logo missing

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#365]
**Describe the bug**
Mint UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

<img width="438" alt="Screen Shot 2022-10-29 at 12 52 44 PM" src="https://user-images.githubusercontent.com/1815379/198846114-c8c58270-464d-4cc0-b1e7-5a466b7d282a.png">

Use the logo from their website: https://mint-ui.github.io/#!/en

**Comment by suchitd11** [comment]
@dustinsgoodman I would like to work on this issue.

**Comment by suchitd11** [comment]
@dustinsgoodman done!
