### ISSUE TITLE
[BUG] Vuestic UI logo issing

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#366]
**Describe the bug**
Vuestic UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

<img width="429" alt="Screen Shot 2022-10-29 at 12 54 59 PM" src="https://user-images.githubusercontent.com/1815379/198846159-f8cf3e0f-481f-4bae-a829-c5daa703ec47.png">

Use the logo from their website: https://vuestic.dev/

**Comment by suchitd11** [comment]
@dustinsgoodman I would like to work on this issue.

**Comment by suchitd11** [comment]
@dustinsgoodman done!
