### ISSUE TITLE
[BUG] Agnostic UI logo missing

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#367]
**Describe the bug**
Vuestic UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

<img width="427" alt="Screen Shot 2022-10-29 at 12 55 03 PM" src="https://user-images.githubusercontent.com/1815379/198846193-6f0976f0-d525-462b-8260-eed1396632d3.png">

Use the logo from their website: https://www.agnosticui.com/

**Comment by zafar-hussain** [comment]
Hi @dustinsgoodman,

can I [Agnostic UI logo](https://github.com/AgnosticUI/agnosticui/blob/master/site/docs/images/agnosticui-illo.svg) UI logo from their GitHub

cheers

**Comment by dustinsgoodman** [comment]
@zafar-hussain Sure!
