### ISSUE TITLE
[BUG] Vue School logo is missing

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#369]
**Describe the bug**
Vue School logo is missing on https://vue.framework.dev/categories/blogs

<img width="502" alt="Screen Shot 2022-10-29 at 1 02 18 PM" src="https://user-images.githubusercontent.com/1815379/198846395-642f2c48-f596-4133-bacd-1692d6a69ab3.png">

Use the one from their website: https://vueschool.io/articles/

**Comment by anandb235** [comment]
I'd like to work on this issue

**Comment by dustinsgoodman** [comment]
You got it @anandb235!
