### ISSUE TITLE
3. Add node.js site to amplify

### ISSUE THREAD

**Issue by kahlie-huff** [thisdot/framework.dev#382]
# Add framework in amplify config for the node.js framework.dev site.

## Background

Each framework.dev site is deployed from the same codebase using amplify. In this ticket, we are adding this new framework to be added to the amplify config so that it gets deployed correctly

## Acceptance

- [x] Add the new framework on amplify.yml
- [x] Test the created PR to make sure that the deployment works as expected

## NOTE:
- You may require someone with AWS access to create the project for you.

**Comment by jdwilkin4** [comment]
This has already been merged in and Dustin helped us create the project on AWS
