### ISSUE TITLE
[BUG] Broken images showing in hero sections for the Qwik and SolidJS sites

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#389]
**Describe the bug**
On the homepage for both the Qwik and SolidJS sites, there is a  broken image sitting on top of the hero section image.

**To Reproduce**
1. Go to [framework.dev](https://pr-388.d27jqwpr7xbhbg.amplifyapp.com/)
2. Click on either the [Qwik](https://qwik.framework.dev/) or [Solidjs](https://solidjs.framework.dev/) resources
3. See the error where there a broken image sitting on top of the hero section image

**Expected behavior**
no broken images should display

**Screenshots**
<img width="1247" alt="Screen Shot 2022-10-31 at 9 56 44 AM" src="https://user-images.githubusercontent.com/67210629/199064877-5a8833be-8c92-486f-b1e6-4d45a34aad4e.png">

<img width="1281" alt="Screen Shot 2022-10-31 at 9 56 56 AM" src="https://user-images.githubusercontent.com/67210629/199064912-db1abed7-8664-4899-bab1-df1a072e66ff.png">

**Comment by morgnism** [comment]
The following items contain fixes for this issue (but are currently blocked from merging to main):
- [qwik](https://github.com/thisdot/framework.dev/pull/357)
