### ISSUE TITLE
Fix hero image white space

### ISSUE THREAD

**Issue by morgnism** [thisdot/framework.dev#391]
# Description

Fix the white space at the bottom of the hero banner images for these framework sites:
- Angular
- Vue

## Context

Angular's hero banner image has some white space at the bottom while other frameworks don't. This is most likely from a bad export of the original Figma image

**Actual**
![Image](https://user-images.githubusercontent.com/9042219/199107526-afb3e8fa-13c9-4af0-8e27-e06fb9beb591.png)

![Image](https://user-images.githubusercontent.com/9042219/199523332-5011df1b-5d7e-45c0-b8b0-8e4e9560bf91.png)

**Expected**
![Image](https://user-images.githubusercontent.com/9042219/199107589-194554cc-0476-4117-823a-6140710830f2.png)

**Comment by jnalei** [comment]
PR #472
