### ISSUE TITLE
Framework.dev landing icons too large

### ISSUE THREAD

**Issue by morgnism** [thisdot/framework.dev#401]
The icons for the various frameworks are too large and touch the boundary filling the white space.

This appears differently when viewing a framework's home page.

**Landing**

![Image](https://user-images.githubusercontent.com/9042219/199552720-4c83b5e5-3ad3-4e25-ba78-4efd057a2a9d.png)

**Other framework's page**
![Image](https://user-images.githubusercontent.com/9042219/199552922-6192ed5b-4ec0-40c9-804d-7e109f4090a8.png)

**Comment by jdwilkin4** [comment]
PR #402
