### ISSUE TITLE
[graphql-pod] 2. Add social image and description

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#418]
# Add framework social image and description

## Background

As an user I would like to have the possibility to share the site on social media and for it to have a nice image and description defined, so that it will increase its visibility and shareability

## Acceptance

- [x] Add metadata description
- [x] Add social image
- [x] Test the site on "https://socialsharepreview.com/"

**Comment by jdwilkin4** [comment]
This merged PR here is responsible for setting up the social media tags and social images for graphql
https://github.com/thisdot/framework.dev/pull/360

Once the graphql.framwork.dev site is setup, then we can test the social share cards.
