### ISSUE TITLE
[BUG] Fix JS Conf Chile and Tech Unite Africa images

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#454]
For the Angular, React and Vue homepages, the JS Conf Chile and Tech Unite Africa images are blurry under the Communities section.

<img width="1226" alt="Screen Shot 2022-11-09 at 3 05 14 PM" src="https://user-images.githubusercontent.com/67210629/200961024-78e74ff8-08e6-4378-a8bc-b5a1b7ca1132.png">

We need to replace those blurry images with higher quality ones.

**Comment by aksy2512** [comment]
I have created a pull request for the same
