### ISSUE TITLE
[BUG] Fix spelling and grammar errors in contributor banner

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#457]
For the each of the framework homepages, there is a contributor banner.
<img width="1193" alt="Screen Shot 2022-11-09 at 5 00 36 PM" src="https://user-images.githubusercontent.com/67210629/200974620-ff663440-e11a-4586-b977-eb52b4dcca1b.png">

There are spelling and grammar errors in this sentence here:
Create a PR if you see mistakes, room for improvement, or new opportunties to help dev team.

It should be changed to this:
Create a PR if you see mistakes, room for improvement, or new opportunities to help the dev team.

Here is the file for the contributor banner
`/framework.dev/packages/system/src/components/homepage/contributor-banner.tsx`

**Comment by jnalei** [comment]
PR #473
