### ISSUE TITLE
Add https://tanstack.com/router/v1 to Svelte, Vue, React, SolidJS, and Qwik framework.dev blog sections

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#460]
As a user, I can see https://tanstack.com/router/v1 listed in our list of resources under the "Tools" section of the Svelte, Vue, React, SolidJS and Qwik versions of the framework.dev site

**Comment by AllStackDev1** [comment]
Is this update across all the packages or should focus on just Qwik only? @kenslachtajr
