### ISSUE TITLE
[graphql-pod] Refactor libraries to address package, repo, image, and language

### ISSUE THREAD

**Issue by WillHutt** [thisdot/framework.dev#462]
`npmPackage` to `package`
- Only showing when/if there is a package of some sort available
- Requires changing href path to be completely flexible
- No hardcoded path
- Update all existing hrefs

`gitHubRepo`  to `repo`
- Only showing when/if there is a repo of some sort available
- Requires changing href path to be completely flexible
- No hardcoded path
- Update all existing hrefs

`language` field?
- Could be taken care of with the tags already?
![Image](https://user-images.githubusercontent.com/20880360/201954970-ab703399-2ec8-468c-876f-f16d10fa68e4.png)

`image` 
- Default image for the framework

**Comment by WillHutt** [comment]
The `language` field is supposed to be the language for that particular entry. So in React's case I assume that would be `React` but I put a [placeholder ](https://github.com/thisdot/framework.dev/blob/main/packages/site/src/data/react/libraries.ts#L37) using the tags per the above statement of 

> We can just merge it with tags and make it the first value

Which can be changed to suit the library. For instance, GraphQL is working like [so](https://github.com/thisdot/framework.dev/blob/main/packages/site/src/data/graphql/libraries.ts#L62).


It is also supposed to be used to look up the package manager for this [here](https://github.com/thisdot/framework.dev/blob/main/packages/system/src/components/cards/library-card.tsx). Admittedly this was the first pass to get it going and to prevent a lot of churn on other pages.

**Comment by dustinsgoodman** [comment]
Didn't we say to make language optional? It doesn't make sense in the case of React as everything is JavaScript or TypeScript but for GraphQL, we needed to be language agnostic.

**Comment by WillHutt** [comment]
Looking into it seems there was talk of making `npmPackage` not required (now just `package`), `gitHubRepo` optional, and/or making it `repo` with the required full URL (this was the route taken), and making an `image` field optional.

It seems the `language` field being optional wasn't discussed, but I have no issues with it being optional. That wouldn't be a difficult change; I believe all you would need to do is change this [here](https://github.com/thisdot/framework.dev/blob/main/packages/system/src/models/library.ts#L42). 

You could also change the `package`, `repo`, and `image` to be optional fields.

[Here](https://thisdot-labs.slack.com/archives/C02JUS8Q7L0/p1668012756723719) is a link to the discussion on this for further clarity.
