### ISSUE TITLE
[Bug] Change hover color on nav for nodejs on framework.dev

### ISSUE THREAD

**Issue by jnalei** [thisdot/framework.dev#477]
Currently the color on hover for the Nodejs reflects a light red and needs to be updated to the Nodejs color palette in light green/light gray.

<img width="238" alt="Screen Shot 2022-11-17 at 6 05 56 PM" src="https://user-images.githubusercontent.com/90362911/202616372-516b423c-d026-420b-aa96-8840501ba9e5.png">

**Comment by morgnism** [comment]
I don't believe this is a bug given the red accents we use in other places, but to be 100% certain, I'd verify this using these 2 methods:
1. Running a sample of the primary colour in the Material Theme Builder (this can be found in a few places figmas) and checking the tonal palettes where there are red (but not the error palette)
2. Check where this colour is coming from and compare it to other frameworks' colour palettes.

**Comment by dustinsgoodman** [comment]
This definitely is a bug. That should be a shade of green. I think the hover state isn't using the theme for some reason.

**Comment by dustinsgoodman** [comment]
cc @Atrophius
