### ISSUE TITLE
Migrate deployments to Netlify Open Source team

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#480]
@danecando and I got a Netlify Open Source project for this repo. Currently, we're deploying via Amplify which hasn't been great and we're generating too many previews per repo. The goal of this issue is to move all of the projects over to Netlify from AWS Amplify. We need to ensure that Netlify's deployment badge is on all the sites as well. He's added an example of what we want in this branch: https://github.com/thisdot/framework.dev/tree/netlify-rocks and deployed it to https://dapper-griffin-b204ab.netlify.app/.  It looks like this currently:
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/1815379/203185566-69cf0d95-dc74-4b9f-99e6-45ba33e15b71.png">

# Acceptance

- [x] add the Netlify Badge to all framework.dev sites and the landing page with new design instructions (see below)
- [x] Deploy all the sites to Netlify. Be sure to copy over secrets as well.
  - [x] landing page
  - [x] react 
  - [x] angular
  - [x] vue
  - [x] qwik
  - [x] solidjs
  - [x] graphql
  - [x] nodejs
  - [x] svelte
- [ ] Migrate DNS from AWS Route 53 to Netlify custom domains
  - [ ] landing page
  - [ ] react 
  - [ ] angular
  - [ ] vue
  - [ ] qwik
  - [ ] solidjs
  - [ ] graphql
  - [ ] nodejs
  - [ ] svelte

# Notes

For the badge, I want to switch to this badge:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1815379/203185651-5ee83ba5-f277-4917-a2b6-0bcd48e28238.png">

which can be fetched from https://www.netlify.com/press/#badges

For the landing page footer, please center the badge and on mobile stack it to be below the This Dot OSS logo: <img width="425" alt="Screenshot 2022-11-21 at 6 36 06 PM" src="https://user-images.githubusercontent.com/1815379/203186015-7dc41f26-14b4-4327-88a0-c3fc832a8a78.png">

For the individual sites, put it below the This Dot OSS logo as well on both desktop and mobile.

**Comment by morgnism** [comment]
Needs Route53 before we close this issue.
