### ISSUE TITLE
Update contributor's section to include all contributors

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/framework.dev#481]
https://vueuse.org/ uses the following way to identify their contributors:

<img width="891" alt="Screenshot 2022-11-21 at 6 42 16 PM" src="https://user-images.githubusercontent.com/1815379/203186754-da40fad7-2a3f-4930-bf98-864da5369f3f.png">

I'm guessing there's an API they use that we could be leveraging to display the same data on our site. We just had hacktoberfest contributions and lot more people have been contributing. We should really highlight these folks more intentionally. We currently have this banner: 
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/1815379/203186918-0df0da9f-4382-4c62-8aa0-968e320d267d.png">

Instead, it should replace the 3 logos with the contributor list style above so that they show up below the text & CTA.

# Acceptance
- Update how contributors are displayed
- Add the contributors' banner to the landing page before the last get started section

**Comment by aksy2512** [comment]
Hi, Can I work on this issue? If assigned, do I need to work on the frontend part of the banner?

**Comment by Zelig880** [comment]
Hei @aksy2512 .. Finish up the other issue that you just assigned dot yourself, and then if still available you can also work on this.

**Comment by jdwilkin4** [comment]
@aksy2512 

Since your last PR was approved, I am assigning you this issue to work on 👍

**Comment by aksy2512** [comment]
@jdwilkin4 I went through the code of https://vueuse.org/. They are not using any API and individually calling each user. Can you please help me determine which API I should use to display the same data?

**Comment by jdwilkin4** [comment]
@aksy2512 

I did some googling and found this stackoverflow answer on how to get the contributors list from the github api
https://stackoverflow.com/questions/36410357/github-v3-api-list-contributors

It looks like this API should give you the information you are looking for
https://api.github.com/repos/thisdot/framework.dev/contributors?anon=1

**Comment by aksy2512** [comment]
ok, Thank you @jdwilkin4. I need one more help. Can you please tell me the specific file in which I have to write the code

**Comment by jdwilkin4** [comment]
@aksy2512 

There is a `ContributorBanner` component in the `homepage.tsx` file. 
That is where the hardcoded array of 3 contributors list current is

```
	<ContributorBanner
	  contributorImages={[
		  "https://github.com/jbachhardie.png",
		  "https://github.com/tvanantwerp.png",
		  "https://github.com/markshenouda.png",
	  ]}
       ></ContributorBanner>
```
You will need to remove that hardcoded array and create a solution that renders all of the contributors for this project. 👍

**Comment by aksy2512** [comment]
I tried it by using the following code inside the Homepage function but the state of contributors is not changing. I also tried using Use effect but it is not working as well
![image](https://user-images.githubusercontent.com/79045568/204805568-05587f8b-a549-4f26-8871-ef311d173b19.png)

**Comment by jdwilkin4** [comment]
Can you open a draft PR?
It will be easier to leave comments on there instead of posting screenshots on the ticket here

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by aksy2512** [comment]
I have linked a Pr and I have commented out the problem in  the code

**Comment by jdwilkin4** [comment]
@aksy2512 

I'll take a look at in a bit. 👍

**Comment by jdwilkin4** [comment]
@aksy2512 

When you are ready to start working on the styles for the banner, here is the design we will be using

<img width="1074" alt="Screen Shot 2022-12-02 at 2 23 54 PM" src="https://user-images.githubusercontent.com/67210629/205400129-0b67dbef-1944-41b5-94d9-3ca8b58b1247.png">

**Comment by aksy2512** [comment]
@jdwilkin4 ok, Thank you , give me 2 days to complete it

**Comment by jdwilkin4** [comment]
@aksy2512 

Just checking in with your progress on this ticket.
How is everything going?

**Comment by aksy2512** [comment]
> @aksy2512 
> 
> Just checking in with your progress on this ticket.
> How is everything going? 

I had some exams in the past couple of days in my university so I wasn't able to focus too much, but now the exams are over and I will continue with the issue

**Comment by aksy2512** [comment]
@jdwilkin4 I had some issues with the previous branch so I have created a new branch and a new pull request and closed the old one. Please have a look at the code that I have pushed
