### ISSUE TITLE
[BUG] replace lower quality and broken images on Vue site

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#483]
**Describe the bug**
We have a couple of blurry and broken quality images that need replacing on the [Vue site](https://vue.framework.dev/).

## Replace the blurry Vue Amsterdam image in the communities section
<img width="1237" alt="Screen Shot 2022-11-22 at 1 30 42 PM" src="https://user-images.githubusercontent.com/67210629/203425082-5695f7fe-d810-40a7-bea6-85bca9b2d66d.png">

## Replace broken image for Nuxt Nation Event
<img width="1463" alt="Screen Shot 2022-11-22 at 1 32 51 PM" src="https://user-images.githubusercontent.com/67210629/203425454-c7fe0650-1146-4edd-95d5-85bb5e2eed30.png">

**Note**
If you are outside of the core This Dot team and interested in working on this issue, please leave a comment below and we can assign it to you.

**Comment by aksy2512** [comment]
Can I work on this issue?

**Comment by jdwilkin4** [comment]
@aksy2512 

The issue has been assigned to you 👍
