### ISSUE TITLE
[BUG] Fix unsecure content

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#487]
There is an image within the repository that is fetched using HTTP instead than HTTPs. This need to be fixed:

AC:
- [x] Change the following image to use HTTPs

http://ng-poland.pl/images/logos/logo-small.png

**Comment by Zelig880** [comment]
hei [aksy2512](https://github.com/aksy2512) you can work on this small task too if you want

**Comment by aksy2512** [comment]
@Zelig880  sure, I can
