### ISSUE TITLE
[solidjs-pod] framework.dev announcement tweet

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#524]
## Background

This will be the initial tweet that goes out to announce the launch of the solidjs.framework.dev.

Tweet must be submitted via this form: https://forms.gle/WjHNGm2vPP5TjnZx9

## Acceptance

- [ ] A tweet about SolidJS being added to the framework.dev site (solidjs.framework.dev) to announce it to the world

**Comment by SDaian** [comment]
> solidjs.framework.dev is here!!! :tada: 
> https://media.giphy.com/media/T9pLxAiWOTywm1H7sd/giphy.gif
> 
> Curious about this simple and performant reactivity framework, check out solidjs.framework.dev.
> Tons of free resources to depth into Reactivity.


> Courses, podcasts, tools, and much more, check out solidjs.framework.dev to discover the magic world of Reactivity :clap:.
> https://media.giphy.com/media/jSuu6dQWhSEQE/giphy.gif
> 

> Performant, powerful, pragmatic, productive. Sounds really good to be true? SolidJS has got you covered :relaxed:
> Check out solidjs.framework.dev to find the best resources.
> 
> https://media.giphy.com/media/BtEw37CXZti8yfq3Ke/giphy.gif
