### ISSUE TITLE
[qwik-pod] Remove Empty Library Sub-Categories

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#545]
# Description
- Most of the library sub-categories are empty. Remove them from navigation until there's more content.

**Comment by AllStackDev1** [comment]
From my findings, the image below shows how the subcategories are been done, would it be ok if i also make a special case for qwik just like we have for graphql.

![Image](https://user-images.githubusercontent.com/36667083/206398292-925e0602-8444-42ed-b0ab-da0ffff3daf8.png)
