### ISSUE TITLE
[node-pod] Add State of Node to Meetups

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#554]
# Description
- Meetups should add State of Node

**Comment by TapaiBalazs** [comment]
@kenslachtajr @dustinsgoodman

Is the State of Node meetup an event that is not yet published?
I don't see it on the meetup pages.
What information should I add to the node entry?

**Comment by dustinsgoodman** [comment]
We don't call it out specifically but it's part of our [State of the Web](https://www.thisdotmedia.com/state-of-the-web/) series. This was the last one: https://www.youtube.com/watch?v=H4qu-_Hl_DA

I'd use the state of the web as the website.
