### ISSUE TITLE
[qwik-graphql-tailwind] Remove empty subcategories from libraries nav

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#585]
# Description

- Most of the library sub-categories are empty. We should remove them from the nav until there's more content.

**Comment by SDaian** [comment]
FYI, you were right @kenslachtajr with https://github.com/thisdot/framework.dev/pull/579 this will be fixed.

**Comment by kenslachtajr** [comment]
Please review your work now that #579 has been merged. Thanks!
