### ISSUE TITLE
[Svelte-pod] Missing tags in the communities and courses data files

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#601]
In the `packages/site/src/data/svelte/courses.ts` and `packages/site/src/data/svelte/communities.ts` files there are missing tags in the `communityTags` and `courseTags` array. This is causing issues for the pre-commit hook. 

Here are screenshots showing the errors of tags being referenced that are not included in the `communityTags` and `courseTags` arrays. 

<img width="988" alt="Screenshot 2023-01-06 at 3 50 35 PM" src="https://user-images.githubusercontent.com/67210629/211118474-7d9d5070-df2f-4b00-b891-43b138a02cab.png">

<img width="1406" alt="Screenshot 2023-01-06 at 3 50 49 PM" src="https://user-images.githubusercontent.com/67210629/211118486-9fa5ad8d-53bc-46d1-b88a-291e2abd6f84.png">

**Comment by kenslachtajr** [comment]
Perhaps we can meet and discuss this? For SvelteKit and Qwik also, we are attempting to hide sections where there is no content, though I am not sure if we made an error in the implementation. Also, Maarteen has a pending PR for the library tags.
