### ISSUE TITLE
nodejs.framework.dev cleanup

### ISSUE THREAD

**Issue by Atrophius** [thisdot/framework.dev#618]
Feedback:

* In libraries, Serverless -> "Serverless Framework"
* Sub-categories under libraries need to be customized. See graphql.framework.dev to find better options.
* Meetups should add state of node
* The list of general conferences we used on the angular/vue/react site for communities was not added to this site and needs to be: https://docs.google.com/spreadsheets/d/1jGZyAFVS4Z8rWwZJ1J_aqRk6JY5pfOutFlLBv7-nqUU/edit

**Comment by morgnism** [comment]
@Atrophius point #2 about the subcategories is vague. Can I get some more details or examples about what we want as "custom"?

**Comment by dustinsgoodman** [comment]
Looking for guidance here but a few categories I thought of:
* frameworks
* middlewares
* ORMs

Definitely want more than this but need to assess the types of libraries included to fully vet.

**Comment by morgnism** [comment]
@mbicknese seems to have updated this a few weeks back (much appreciated), and I've added a few more.

Here's what we have with a few more categories:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/9042219/213026850-bfd4db61-8959-4799-8bac-318747715941.png">

Thoughts on this?

**Comment by dustinsgoodman** [comment]
In general, less is more. I'd omit the following:
- API LIbraries
- Serverless
- Tooling (there's a whole tools top level nav)
- Email Client
- CLI (unless there's a better name)

Also, rename AUTH to "Auth"

**Comment by dustinsgoodman** [comment]
Looking more closely - web servers should be omitted too. API Libraries, Web Servers, and Tooling are all just frameworks

**Comment by morgnism** [comment]
Shorter list:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/9042219/213029114-945e8c2f-26f9-468f-a9f1-1ed49e9adcd6.png">

**Comment by morgnism** [comment]
Given what you said about this list, check the graphql site and put some thoughts on that too because this issue suggested more categories like that one.

**Comment by dustinsgoodman** [comment]
There's another issue for that one lingering somewhere to fix it. That looks good to me though. Thanks!
