### ISSUE TITLE
Add data loaders JS Marathon to courses

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/framework.dev#700]
# Background
- Our data loaders js marathon is missing from courses

**Comment by iansamz** [comment]
![Image](https://user-images.githubusercontent.com/15368874/220603096-b895023e-e151-422d-ba03-df092429ba91.png)

The data loaders have been added. This should be closed

**Comment by dustinsgoodman** [comment]
2 outstanding issues:

1. The logo should be This Dot and not Star's profile image
2. Clicking on the card does not go to YouTube


![Image](https://github.com/thisdot/framework.dev/assets/1815379/b707bfb7-b5d7-4efb-8ff4-e852ead0077b)
