### ISSUE TITLE
[Angular site] - replace low quality image for Angular Playground

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#711]
We should replace this low quality hard to see image for [Angular Playground](https://angular.framework.dev/categories/tools) here

<img width="500" alt="Screenshot 2023-02-17 at 2 32 41 PM" src="https://user-images.githubusercontent.com/67210629/219807973-eb26376b-414c-4b02-911a-5edcca7869a3.png">

## Acceptance criteria 

- [ ] replace the current img url with a higher quality image or the default Angular logo

**Comment by BigAB** [comment]
With the dimensions for where that image goes, I think it would be good to just use the "crayon-esque" version of the Angular logo from the middle of their logo



![Image](https://user-images.githubusercontent.com/76821/223210886-8ba6755f-1f08-4593-8092-b8a22161c688.png)
