### ISSUE TITLE
[Node site] - replace blurry image in coures section 

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/framework.dev#720]
In the courses section for the [homepage](https://nodejs.framework.dev/), we need to replcae the following blurry image

<img width="796" alt="Screenshot 2023-02-17 at 5 18 33 PM" src="https://user-images.githubusercontent.com/67210629/219823854-2cc1ef66-1b01-43e0-84fc-62afb54c3831.png">

## Acceptance 

- [ ] replace blurry image for Node course with high quality one

**Comment by BigAB** [comment]
I could only find a "less blurry" image
https://yt3.googleusercontent.com/ytc/AL5GRJXtuktEGarPtsDfBBlRuEsXFSEreRnyz4eYchGQ1w=s176-c-k-c0x00ffffff-no-rj

**Comment by BigAB** [comment]
Actually, I guess there is this one
https://yt3.googleusercontent.com/ytc/AL5GRJXtuktEGarPtsDfBBlRuEsXFSEreRnyz4eYchGQ1w=s900-c-k-c0x00ffffff-no-rj
