### ISSUE TITLE
[Lit-Mobx-Vaadin] Resources Collection for a LitElement framework.dev Page

### ISSUE THREAD

**Issue by Amdrel** [thisdot/framework.dev#760]

**Comment by jesus4497** [comment]
https://docs.google.com/document/d/18Er5Uigj8EPqUAzfDd46B1zMPz-Xz3Q3sS24oSvD3AI/edit#heading=h.pghbqsobegv4

**Comment by dustinsgoodman** [comment]
@jesus4497 can you tell me what happened with this?

**Comment by jesus4497** [comment]
@dustinsgoodman this was ready for a last review, but it is ready!

**Comment by dustinsgoodman** [comment]
Where's the deployment for this?

**Comment by jesus4497** [comment]
oh! The scope for this was to only gather the resources in the doc, we don't have a PR exactly

**Comment by dustinsgoodman** [comment]
Got it! Thank you!
