### ISSUE TITLE
Add zod for data validation

### ISSUE THREAD

**Issue by tvanantwerp** [thisdot/framework.dev#782]
**Is your feature request related to a problem? Please describe.**
Currently we have models for data as TypeScript types and interfaces. This provides some level of validation (e.g., `12345` is not a string and can't be used for a `href` value to link out to a resource), but it's limited. Using a data validation library like [zod](https://zod.dev) would let us be more specific and validate that `href` is a valid URL with a simple schema like `href: z.string().url()`.

**Describe the solution you'd like**
Add the zod library and write the data schemas with zod. Then derive the types from the zod schema.

**Describe alternatives you've considered**
- **Manual review of data quality.** It's time-consuming and prone to errors. Easier if basic validation is automated and results shown in PRs.
- **Write our own data validation functions.** Needlessly complex and time consuming compared to just using a library like zod.

**Additional context**
For example, here's what a refactored version of the `Podcast` interface would look like with zod. Note how `rss` and `href` now must be valid URLs, `image` must be a valid URL that also matches a regex where it ends with one of the specified image extensions, and the _short_ description is explicitly limited to 280 characters.

```ts

import { z } from 'zod';

export Podcast {
	title: z.string(),
	image: z.string().url().regex(/.*\.(png|jpg|gif)$/),
	description: z.string().length(280),
	rss: z.string().url(),
	hosts: z.array(z.string()),
	href: z.string().url(),
}

export type Podcast = z.infer<typeof Podcast>;
```

**Comment by dustinsgoodman** [comment]
Considering 90% of this site is built at build time and not runtime, would zod still be as impactful?

**Comment by dustinsgoodman** [comment]
Astro content collections makes this unnecessary as it uses zod under the hood. #783 will resolve this.
